language: python
python:
  - '3.7'
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_dc2e35eaf6d8_key -iv $encrypted_dc2e35eaf6d8_iv
    -in lada-api-f796c5679cd9.json.enc -out lada-api-f796c5679cd9.json -d
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=api setup.py test
after_success:
  - coveralls
before_deploy: "./inject_varenv"
deploy:
  provider: gae
  keyfile: lada-api-f796c5679cd9.json
  project: lada-api-250821
  skip_cleanup: true
  on:
    tags: true
    branch: master
