language: python
python:
  - '3.7'
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_dc2e35eaf6d8_key -iv $encrypted_dc2e35eaf6d8_iv
    -in lada-api-c9b5e4dfbe69.json.enc -out lada-api-c9b5e4dfbe69.json -d
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=api setup.py test
after_success:
  - coveralls
before_deploy:
  - echo -e "env_variables:" >>app.yaml
  - bash varenv.sh
deploy:
  provider: gae
  keyfile: lada-api-c9b5e4dfbe69.json
  project: lada-api-250623

