language: python
python:
  - '3.7'
sudo: required
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=api setup.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
